# Generated by Django 4.2.7 on 2023-11-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('V', 'Vacaciones'), ('F', 'Feriado'), ('S', 'Suspension de actividades'), ('SPM', 'Suspension de actividades PM'), ('P', 'Periodo Lectivo'), ('SE', 'Suspension de evaluaciones'), ('C', 'Ceremonia'), ('E', 'EDDA'), ('EV', 'Evaluación'), ('A', 'Ayudantías'), ('H', 'Hito académico'), ('SA', 'Secretaria Académica'), ('O', 'OAI')], default='V', max_length=20)),
                ('segmentos', models.ManyToManyField(to='UsmCalendar.segmento')),
            ],
        ),
    ]
