# Generated by Django 4.2.7 on 2023-11-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsmCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='segmentos',
            field=models.ManyToManyField(choices=[('Comunidad USM', 'Comunidad USM'), ('Estudiantes', 'Estudiantes'), ('Profesor', 'Profesor'), ('Jefe de Carrera', 'Jefe de Carrera')], to='UsmCalendar.segmento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('V', 'Vacaciones'), ('F', 'Feriado'), ('S', 'Suspensión de actividades'), ('SPM', 'Suspensión de actividades PM'), ('P', 'Periodo Lectivo'), ('SE', 'Suspensión de evaluaciones'), ('C', 'Ceremonia'), ('E', 'EDDA'), ('EV', 'Evaluación'), ('A', 'Ayudantías'), ('H', 'Hito académico'), ('SA', 'Secretaría Académica'), ('O', 'OAI')], default='V', max_length=20),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
