# Generated by Django 4.2.7 on 2023-11-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsmCalendar', '0002_alter_evento_segmentos_alter_evento_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('segmentos', models.ManyToManyField(to='UsmCalendar.segmento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='roles',
            field=models.ManyToManyField(to='UsmCalendar.rol'),
        ),
    ]
