# Generated by Django 4.2.7 on 2023-11-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsmCalendar', '0003_rol_evento_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='roles',
        ),
        migrations.AlterField(
            model_name='segmento',
            name='nombre',
            field=models.CharField(choices=[('Comunidad USM', 'Comunidad USM'), ('Estudiantes', 'Estudiantes'), ('Profesor', 'Profesor'), ('Jefe de Carrera', 'Jefe de Carrera')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
