# Generated by Django 4.2.7 on 2023-11-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsmCalendar', '0004_remove_evento_roles_alter_segmento_nombre_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='segmentos',
            field=models.ManyToManyField(to='UsmCalendar.segmento'),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
